## General KNN
#### with Required functions

In [894]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import timeit
import itertools

df = pd.read_csv('iris.csv')
df = df.apply(np.random.permutation,axis=0)
data = df.values
data

x = data[:,:4]
y = data[:,4:]

x_train = x[:120]
x_test = x[120:]

y_train = y[:120]
y_test = y[120:]

class KNN:
    def __init__(self, k=1):
        self.k = k
    
    def train(self,x,y):
        self.x = x
        self.y = y
    
    def predict(self,x):
        label = []
        for i in range(x.shape[0]):
            diff = self.x - x[i]
            diff = diff ** 2
            euc  = np.sum(diff,axis = 1)
            euc  = euc ** 0.5
            indexes = np.argpartition(euc,self.k) #First k minimum distances
            indexes = indexes[0:self.k]
            
            
            l = list(self.y[:,0][indexes])
            dictionary = dict((x,l.count(x)) for x in set(l))
            max_value = max(dictionary,key = dictionary.get)
            label.append(max_value)
        return label
    
    def findBestK(self,validation_x,validation_y,n):
        array = np.zeros(n)
        for i in range(1,n):
            self.k = i;
            array[i] = self.evaluate(validation_y,self.predict(validation_x))
            
        self.k = np.where(array == np.max(array))[0][0]
        #return self.k,np.max(array)
    
    def evaluate(self,y,l):
        count = 0
        for i in range(y.shape[0]):
            if(y[i] == l[i]):
                count += 1
                
        accuracy = (count/len(y))*100
        return accuracy

### Test KNN

In [895]:
clf = KNN(3)
clf.train(x_train,y_train)
clf.findBestK(x_test,y_test,10)
labels = clf.predict(x_test)
clf.evaluate(y_test,labels)

56.666666666666664

### Normalize function

In [896]:
def normalize(feature,method = 0): # Normalize
    if(method == 0): #standard Score
        m = feature.mean()
        sd = feature.std()
        feature = (feature - m)/sd
    if(method == 1): #minmax Scaling
        maxi = feature.max()
        mini = feature.min()
        feature = ((feature - mini)/(maxi - mini))
    return feature

# Course Recommendation System

In [897]:
df = pd.read_excel('Course_Advisory_Data.xlsx')

##### Deleting irrelevant rows from data

In [898]:
del_vals = df[(df.Semester == 20111) | (df.Semester == 20121) | (df.Semester == 20123) | (df.Semester == 20131)].index.values
df.drop(del_vals,axis = 0,inplace = True)

##### Replace Spaces with "_" so we can access it as an object of DataFrame.

In [899]:
#Replace Spaces with "_" so we can access it as an object of DataFrame.
df.columns = df.columns.str.replace(' ', '_')

#Removing spaces can cause abormalities in column names. We can clear it by removing those abnormalities.
df = df.rename(columns={'Sr._No':'Sr_No'})

##### Deleting MS Courses

In [900]:
f = open("course_del.txt",'r')
l = [i[:-1] if i[-1] == '\n' else i for i in f]
for i in l:
    del_vals = df[df.Course_Title == i].index.values
    df.drop(del_vals,axis = 0,inplace = True)

##### Changing Semester Names to sort them sequencely

In [901]:
v = df.Semester == "Spring 2016"
df.Semester[v] = "2016A"
v = df.Semester == "Summer 2016"
df.Semester[v] = "2016B"
v = df.Semester == "Fall 2016"
df.Semester[v] = "2016C"

v = df.Semester == "Spring 2017"
df.Semester[v] = "2017A"
v = df.Semester == "Summer 2017"
df.Semester[v] = "2017B"
v = df.Semester == "Fall 2017"
df.Semester[v] = "2017C"

v = df.Semester == "Spring 2018"
df.Semester[v] = "2018A"
v = df.Semester == "Summer 2018"
df.Semester[v] = "2018B"
v = df.Semester == "Fall 2018"
df.Semester[v] = "2018C"

v = df.Semester == "Spring 2019"
df.Semester[v] = "2018A"
v = df.Semester == "Summer 2019"
df.Semester[v] = "2019B"
v = df.Semester == "Fall 2019"
df.Semester[v] = "2019C"

df

C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Sr_No,Semester,Course_Code,Course_Title,Credit_Hours,Grade,Grade_Point,SGPA,CGPA,Warning
0,16016,2016C,EE182,Basic Electronics,3,A,4.00,2.92,2.92,0
1,16016,2016C,CL101,Introduction to Computing Lab,1,B,3.00,2.92,2.92,0
2,16016,2016C,CS101,Introduction to Computing,3,C-,1.67,2.92,2.92,0
3,16016,2016C,SS111,Islamic and Religious Studies,3,B+,3.33,2.92,2.92,0
4,16016,2016C,SS101,English Language,3,A-,3.67,2.92,2.92,0
...,...,...,...,...,...,...,...,...,...,...
62591,18408,2018A,MT224,Differential Equations (Cal II),3,B-,2.67,3.43,3.07,0
62592,18408,2018A,SS152,Communication & Presentation Skills,2,A,4.00,3.43,3.07,0
62593,18408,2018A,SS113,Pakistan Studies,3,A-,3.67,3.43,3.07,0
62594,18408,2018A,EE227,Digital Logic Design,3,B+,3.33,3.43,3.07,0
62595,18408,2018A,EL227,Digital Logic Design - Lab,1,A,4.00,3.43,3.07,0

### Separating Departments

In [902]:
d = df
df["Dept"] = None

department = ["EE.txt","AF.txt"]

Ei = []
f = open("EE.txt",'r')
dept = [i[:-1] if i[-1] == '\n' else i for i in f]
for i in dept:
    Ei.extend(df[df.Course_Title == i].Sr_No.values.tolist())

Bi = [];
dept = []
f = open("AF.txt",'r')
dept = [i[:-1] if i[-1] == '\n' else i for i in f]
for i in dept:
    Bi.extend(df[df.Course_Title == i].Sr_No.values.tolist())



for i in Ei:
    l = df[df.Sr_No == i].index.tolist()
    for j in l:
        df.Dept.loc[j] = "EE"
    
for i in Bi:
    l = df[df.Sr_No == i].index.tolist()
    for j in l:
        df.Dept.loc[l] = "AF"

df.Dept.fillna("CS", inplace = True)

C:\Users\Waqar_Shakeel\Anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [903]:
#df.Dept.loc[df[(df.Course_Title == "Electronic Devices and Circuits") & (df.Dept == "CS")].index.tolist()] = "EE"
#df[(df.Course_Title == "Electronic Devices and Circuits") & (df.Dept == "CS")]
df.groupby("Dept").count()

,Sr_No,Semester,Course_Code,Course_Title,Credit_Hours,Grade,Grade_Point,SGPA,CGPA,Warning
Dept,,,,,,,,,,
AF,26729,26729,26729,26729,26729,26729,26729,26717,26729,26729
CS,26322,26322,26322,26322,26322,26322,26322,26293,26322,26322
EE,7766,7766,7766,7766,7766,7766,7766,7758,7766,7766

## Formatting Data and Custom KNN

In [904]:
d = pd.DataFrame(columns = ['Dept','Courses',"Grade_Point",'SGPA', 'CGPA' , 'Warning',"New_Courses"])
roll_numbers = df.Sr_No.unique()
roll_numbers.sort()

for j in roll_numbers:
    v = df[df.Sr_No == j]
    sem = v.groupby(["Sr_No"])
    sem = sem.Semester.value_counts()
    sem = [i[1] for i in sem.index]
    sem.sort()
    semester_course = []
    for i in sem:
        semester_course.append(df[(df.Sr_No == j) & (df.Semester == i)])

    for i in range(len(semester_course) - 1):
        #gp = len(semester_course[i].Grade_Point.values) * semester_course[i].Grade_Point.values.mean()
        #d.loc[len(d)] = semester_course[i].Course_Code.values,semester_course[i].Grade_Point.values,semester_course[i].SGPA.max(),semester_course[i].CGPA.max(),semester_course[i].Warning.values.max(),semester_course[i+1].Course_Code.values
        d.loc[len(d)] = np.unique(semester_course[i].Dept.values)[0],semester_course[i].Course_Title.values,semester_course[i].Grade_Point.values,semester_course[i].SGPA.max(),semester_course[i].CGPA.max(),semester_course[i].Warning.values.max(),semester_course[i+1].Course_Title.values

In [905]:
d

,Dept,Courses,Grade_Point,SGPA,CGPA,Warning,New_Courses
0,CS,"[Calculus - I, Introduction to Computing, Basi...","[0.0, 0.0, 0.0, 3.67, 0.0, 0.0, 3.0]",0.82,0.82,2,"[Linear Algebra, English Composition, Introduc..."
1,CS,"[Linear Algebra, English Composition, Introduc...","[0.0, 3.0, 0.0, 1.33, 0.0, 1.0]",1.00,1.50,2,"[Linear Algebra, Introduction to Computing, Ba..."
2,CS,"[Linear Algebra, Introduction to Computing, Ba...","[1.67, 1.67, 3.0, 1.67, 0.0]",2.07,2.38,2,"[Islamic and Religious Studies, Computer Progr..."
3,CS,"[Islamic and Religious Studies, Computer Progr...","[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",2.00,2.33,2,"[Digital Logic Design - Lab, Digital Logic Des..."
4,CS,"[Digital Logic Design - Lab, Digital Logic Des...","[1.33, 0.0]",0.33,2.04,2,"[Digital Logic Design, Probability and Statist..."
...,...,...,...,...,...,...,...
6030,EE,"[Linear Algebra, Linear Circuit Analysis - Lab...","[2.67, 4.0, 2.33, 3.67, 3.33, 3.33, 3.67, 3.0]",3.11,2.88,0,"[Introduction to Computing - Lab, Physics for ..."
6031,EE,"[Introduction to Computing - Lab, Physics for ...","[4.0, 2.67, 1.0, 4.0, 2.67, 2.67, 3.0, 3.33]",2.63,2.63,0,"[Electronic Devices and Circuits, Data Structu..."
6032,EE,"[Differential Equations, Programming Fundament...","[3.67, 4.0, 4.0, 1.67, 4.0, 3.67, 3.67, 4.0]",3.45,3.38,0,"[Applied Calculus, Introduction to Computing -..."
6033,EE,"[Linear Circuit Analysis - Lab, Programming Fu...","[1.0, 0.0, 3.33, 3.0, 3.67, 0.0, 1.33]",2.69,2.69,0,"[Programming Fundamentals, Programming Fundame..."
6034,EE,"[Programming Fundamentals, Programming Fundame...","[0.0, 0.0]",0.00,2.06,0,"[Differential Equations, Electronic Devices an..."

##### Saving it as a file

In [906]:
d.to_pickle("save_data_file.pkl")

In [907]:
unpickled_df = pd.read_pickle("save_data_file.pkl")
unpickled_df

,Dept,Courses,Grade_Point,SGPA,CGPA,Warning,New_Courses
0,CS,"[Calculus - I, Introduction to Computing, Basi...","[0.0, 0.0, 0.0, 3.67, 0.0, 0.0, 3.0]",0.82,0.82,2,"[Linear Algebra, English Composition, Introduc..."
1,CS,"[Linear Algebra, English Composition, Introduc...","[0.0, 3.0, 0.0, 1.33, 0.0, 1.0]",1.00,1.50,2,"[Linear Algebra, Introduction to Computing, Ba..."
2,CS,"[Linear Algebra, Introduction to Computing, Ba...","[1.67, 1.67, 3.0, 1.67, 0.0]",2.07,2.38,2,"[Islamic and Religious Studies, Computer Progr..."
3,CS,"[Islamic and Religious Studies, Computer Progr...","[2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",2.00,2.33,2,"[Digital Logic Design - Lab, Digital Logic Des..."
4,CS,"[Digital Logic Design - Lab, Digital Logic Des...","[1.33, 0.0]",0.33,2.04,2,"[Digital Logic Design, Probability and Statist..."
...,...,...,...,...,...,...,...
6030,EE,"[Linear Algebra, Linear Circuit Analysis - Lab...","[2.67, 4.0, 2.33, 3.67, 3.33, 3.33, 3.67, 3.0]",3.11,2.88,0,"[Introduction to Computing - Lab, Physics for ..."
6031,EE,"[Introduction to Computing - Lab, Physics for ...","[4.0, 2.67, 1.0, 4.0, 2.67, 2.67, 3.0, 3.33]",2.63,2.63,0,"[Electronic Devices and Circuits, Data Structu..."
6032,EE,"[Differential Equations, Programming Fundament...","[3.67, 4.0, 4.0, 1.67, 4.0, 3.67, 3.67, 4.0]",3.45,3.38,0,"[Applied Calculus, Introduction to Computing -..."
6033,EE,"[Linear Circuit Analysis - Lab, Programming Fu...","[1.0, 0.0, 3.33, 3.0, 3.67, 0.0, 1.33]",2.69,2.69,0,"[Programming Fundamentals, Programming Fundame..."
6034,EE,"[Programming Fundamentals, Programming Fundame...","[0.0, 0.0]",0.00,2.06,0,"[Differential Equations, Electronic Devices an..."

##### Dividing data into Train and Test Sets

In [908]:
x = d.values[:,:6]
y = d.values[:,6:]

x_train = x[:4500]
x_test = x[4500:]

y_train = y[:4500]
y_test = y[4500:]

### My Formula for Distance

#### diff[i] = (np.sum((self.x[i] - x) ** 2) + (Difference_of_Courses) ** 2 + np.sum(grade_diff ** 2)) ** 0.5

   The variable self.x and x contains CGPA, SGPA and Warning. We calculate sum of squares of their difference. Difference_of_Courses increase if courses does not match. The variable grade_diff is the vector contains grade points of all the courses. So we calculate difference of grade points of each similar course and get the euclidean distance.

#### Custom KNN

In [909]:
class KNN:
    def __init__(self, k=1):
        self.k = k
    
    
    def train(self,x,y):
        self.dept = x[:,0]
        self.courses = x[:,1]
        self.grades = x[:,2]
        self.x = x[:,3:]
        self.y = y
        self.warning = False
        
    def predict(self,x):
        department = x[0]
        x_courses = x[1]
        x_grades  = x[2]
# =============================================================================
#         for i in range(len(self.courses)):
#             c = 0
#             for j in self.courses[i]:
#                 if j in x_courses:
#                     c+=1
#             self.equal_courses[i] = c
#             
#         normalize(self.equal_courses,1)
# =============================================================================
        x = x[3:]
        self.warning = (x[2] != 0)
        #self.warning = False
        
        #grade_similarity = np.zeros(self.courses.shape[0])
        #course_similarity = np.zeros(self.courses.shape[0])
        #for i in range(len(self.courses)):
        #    points = 0
        #    grad_p = 50
        #    for j in range(len(x_courses)):
        #        if (not(x_courses[j] in self.courses[i])):
        #            points += 1
        #        else:
        #            ind = x_courses[j] == self.courses[i]
        #            grad_p -= np.abs((np.array(self.grades[i])[ind][0] - x_grades[j]))
                    
        #    course_similarity[i] = points
        #    grade_similarity[i] = grad_p
            
            
        #label = []
        diff = np.zeros(self.x.shape[0])
        for i in range(self.x.shape[0]):
            if(department == self.dept[i]):
                #print(self.x[i])
                points = 0
                grade_diff = np.zeros(len(x_courses))
                for j in range(len(x_courses)):
                    if (not(x_courses[j] in self.courses[i])):
                        points += 1
                        grade_diff[j] = 4
                    else:
                        #print(i,j,len(self.grades[i]),len(x_grades))
                        ind = x_courses[j] == self.courses[i]
                        #print(self.grades[i][ind])
                        grade_diff[j] = np.abs((self.grades[i][ind][0] - x_grades[j]))
                           
                #print("Sum",np.sum((np.array(self.x[i]) - np.array(x))))
                #print("FSUM",(np.sum((np.array(self.x[i]) - np.array(x)) ** 2) + points  ** 2 + np.sum(grade_diff ** 2)) ** 0.5)
                diff[i] = (np.sum((np.array(self.x[i]) - np.array(x)) ** 2) + points  ** 2 + np.sum(grade_diff ** 2)) ** 0.5
            else:
                diff[i] = 99999999
            #diff = diff ** 2
            #self.equal_courses
            #euc  = np.sum(diff,axis = 1)
            #euc  = euc ** 0.5
        indexes = np.argpartition(diff,self.k) #First k minimum distances
        indexes = indexes[0:self.k]

        
        final_list = []
        temper = []
        l = self.y[:,0][indexes].tolist()
        for i in range(len(l)):
            temper.extend(l[i].tolist())
        
        #print(temper)
        
        dictionary = dict((x,temper.count(x)) for x in set(temper))
        dic = sorted(dictionary.items(), key=lambda x: x[1],reverse = True) 
        
        ind = x_grades == 0
        final_list.extend(x_courses[ind])

        #return final_list
        #print("CDT_HR",cdt_hr)
        cdt_hr = np.sum([p["Cr.Hrs"].loc[p[p.Title == i].index.tolist()].values.tolist()[0] 
                         if len(p["Cr.Hrs"].loc[p[p.Title == i].index.tolist()].values.tolist()) != 0 
                         else 0 
                         for i in final_list])
        #cdt_hr = len(final_list)
        #cdt_hr = 0
        
        
        max_cor = 19
        if(self.warning):
            max_cor = 14

        for i in dic:
            if(cdt_hr >= max_cor):
                break

            if(not(i[0] in final_list)):
                if(check_pre_req(i[0],x_courses)):
                    final_list.append(i[0])
                    if(len(p["Cr.Hrs"].loc[p[p.Title == i[0]].index.tolist()].values.tolist()) == 0):
                        cdt_hr += 3    
                    else:
                        cdt_hr += p["Cr.Hrs"].loc[p[p.Title == i[0]].index.tolist()].values.tolist()[0]
        
        while(cdt_hr > max_cor):
            c = final_list.pop(len(final_list) - 1)
            if(len(p["Cr.Hrs"].loc[p[p.Title == c].index.tolist()].values.tolist()) == 0):
                cdt_hr -= 3    
            else:
                cdt_hr -= p["Cr.Hrs"].loc[p[p.Title == c].index.tolist()].values.tolist()[0]
            #final_list = set(final_list)
            
        return final_list

# =============================================================================       
#            #lab = [i for i, x in enumerate(final_list) if "Lab" in x]
#            #crd_hr = (len(lab) * 1) + (len(final_list)-len(lab)) * 3
#            #while(crd_hr > 19):
#                
#            #    while(num)
#                
#            #    final_list.remove(final_list[])
#            
#            #return l[random.randrange (0,self.k,1)]
#
#            #temper = np.array(sorted(set(temper)))
#
#            
#            #lab_list  = ['L' in i for i in temper]
#            #lab_list  = temper[lab_list]
#            #cour_list = [not('L' in i) for i in temper]
#            #cour_list = temper[cour_list]


#             lab_list = lab_list.tolist()
#             cour_list = cour_list.tolist()
#             
#             final_list = []
#             count = 0
#             for i in range(len(cour_list)):
#                 
#                 course_for_lab = cour_list[i]
#                 list1 = list(course_for_lab)
#                 list1[1] = 'L'
#                 course_for_lab = ''.join(list1)
#                
#                 if(course_for_lab in lab_list):
#                     final_list.append(cour_list[i])
#                     final_list.append(course_for_lab)
#                     count = count + 4
#                     if(count >= 16):
#                         break
#             
#             cour_list = set(cour_list) - set(final_list)
#             for i in cour_list:
#                 if count >= 19:
#                     final_list.append(cour_list[i])
# =============================================================================
            
           # return final_list


    
    def evaluate(self,y,l):
        count = 0
        accuracy = 0
        l = l.tolist()
        l = np.array(l)
        for i in y:
            if str(i) in l:   
                count += 1
                
        if(len(y) != 0):
            accuracy = (float(count)/float(len(y)))*100
        return accuracy

#### Testing Custom KNN (adviceMe())

In [910]:
#for k in range(1,10):
k = 10
clf = KNN(k)
clf.train(x_train,y_train)
    
labels = []
#evaluated_list = []
i = 19
#k = 3
#for i in range(1500):
labels = adviseMe(x_train[i],k) #clf.predict(x_train[i])
#print(x_train[0,:1].tolist()[0])
prev_courses = x_train[i,1:2].tolist()[0]
print("Previous Courses")
print(prev_courses)
print("")
print("New Courses")
print(y_train[i,:1].tolist()[0])
print("")
comapre_course(labels,y_train[i,:1].tolist()[0])
#comapre_course(labels,x_train[0,:1].tolist()[0])
accuracy = clf.evaluate(labels,y_train[i])
#evaluated_list.append(accuracy)
#print(accuracy)
#print(evaluated_list)
#print("K = ",k," ___ ",sum(evaluated_list)/len(evaluated_list))

Previous Courses
['Comp. Organization and Assembly Lang.' 'Discrete Structures'
 'Data Structures' 'Pakistan Studies'
 'Comp. Organization and Assembly Lang. Lab' 'Fundamentals of Management']

New Courses
['Computer Architecture' 'Database Systems' 'Operating Systems'
 'Principles of Marketing' 'Operating Systems Lab'
 'Technical and Business Writing' 'Database Systems Lab' 'Data Mining'
 'Numerical Methods' 'Design and Analysis of Algorithms'
 'Mobile Computing' 'Software Engineering']

Predicted

['Computer Architecture', 'Data Mining', 'Principles of Marketing', 'Operating Systems', 'Numerical Methods', 'Design and Analysis of Algorithms']

Matched

Computer Architecture
Data Mining
Principles of Marketing
Operating Systems
Numerical Methods
Design and Analysis of Algorithms

In [911]:
def adviseMe(student_record,k):
    labels = []
    evaluated_list = []

    clf = KNN(k)
    clf.train(x_train,y_train)    
    labels = clf.predict(student_record)
    return labels

##### For Result Visualization Help

In [912]:
def comapre_course(x,y):
    print("Predicted")
    print("")
    print(x)
    print("")
    print("Matched")
    print("")
    if(len(x) < len(y)):
        for i in range(len(x)):
            if(x[i] in y):
                print(x[i])
    else:
        for i in range(len(y)):
            if(y[i] in x):
                print(y[i])
    print("")

In [913]:
d.loc[5]

Dept                                                          CS
Courses        [Digital Logic Design, Probability and Statist...
Grade_Point                     [1.67, 1.0, 1.33, 0.0, 0.0, 0.0]
SGPA                                                           1
CGPA                                                        1.84
Warning                                                        2
New_Courses    [Probability and Statistics, Object Oriented P...
Name: 5, dtype: object

In [914]:
codeToTitle = pd.read_excel('Prerequisites of All Courses.xlsx')
codeToTitle.drop(['Sr#', 'Equivalence','Pre Req.',"Status","Type"], axis=1, inplace=True)

p = pd.read_excel('Prerequisites of All Courses.xlsx')
index = p.groupby("Title")["Pre Req."].value_counts().index
pre_req = {}
for i in index:
    pre_req.update({i[0]:[x.strip() for x in i[1].split(',')]})
    
pre_list = p["Pre Req."].loc[p[p.Title == "Basic Electronics"].index.tolist()].values.tolist()
p["Pre Req."] = p["Pre Req."].fillna("ZZZ")
p

,Sr#,Code,Title,Type,Cr.Hrs,Equivalence,Status,Pre Req.
0,1,CL103,Computer Programming Lab,Lab,1.0,397,Active,"CL101, CS101"
1,2,CL203,Database Systems Lab,Lab,1.0,726,Active,CS201
2,3,CL205,Operating Systems Lab,Lab,1.0,727,Active,CS201
3,4,CL210,Data Structures and Algorithms - Lab,Lab,1.0,1010,Active,"CS214, CL214"
4,5,CL214,Programming Fundamentals - Lab,Lab,1.0,397,Active,"EL116, EE116"
...,...,...,...,...,...,...,...,...
1315,1316,CS480,Network Programming Lab,Lab,3.0,43,Dormant,ZZZ
1316,1317,CS639,Computer Aided Modeling and Simulation,Taught Course,3.0,1203,Active,ZZZ
1317,1318,SE505,Model Based Testing,Taught Course,3.0,1169,Active,ZZZ
1318,1319,CS110,Computer Programming,Taught Course,3.0,208,Dormant,ZZZ
1319,1320,MG208,IT Management,Taught Course,3.0,118,Dormant,ZZZ

In [915]:
def check_pre_req(course,list_previous_course):
    pre_list = p["Pre Req."].loc[p[p.Title == course].index.tolist()].values.tolist()
    
    if(len(pre_list) == 0 or pre_list[0] == "ZZZ"):
        return True
    cor = [x.strip() for x in pre_list[0].split(',')]
    cor = p["Title"].loc[p[p.Code == cor[0]].index.tolist()].values.tolist()
    if(cor[0] in list_previous_course):
        return True
    else:
        return False

In [916]:
check_pre_req("Calculus - I",["Calculus - II","Basic Electronics","Digital Logic Design"])

True

In [917]:
p["Cr.Hrs"].loc[p[p.Title == "Computer Programming Lab"].index.tolist()].values.tolist()[0]

1.0